keys:
  - &fushiii age1vqkhlwzs9hhsnl2yms37p4fctpvaznta5sk7kshxvmj0u9u5c3jqvk4nh7
  - &diegofariasm age1hnhysqxhry7a5n8d5u0x2gqq00qgj8a49yhtpu0y4tqmktkww52s4qj2h8

creation_rules:
  - path_regex: users/fushiii/secrets/[^/]+\.(yaml|json)$
    age: *fushiii
  - path_regex: users/diegofariasm/secrets/[^/]+\.(yaml|json)$
    age: *diegofariasm
