keys:
  - &fushiii age1vqkhlwzs9hhsnl2yms37p4fctpvaznta5sk7kshxvmj0u9u5c3jqvk4nh7

creation_rules:
  # User secrets.
  # Should be ssh keys, and some other things
  # related solely to the user.
  - path_regex: users/fushiii/secrets/[^/]+\.(yaml|json)$
    age: *fushiii
  
