# This is a custom data for this project where it lists the images found in
# this flake. This can range from NixOS configurations intended to be deployed
# for servers and desktops to installers.
#
# The data is then used for the image creation functions found in `flake.nix`.
# Each of the entry should correspond to one of the hosts in `./hosts/`
# directory.
#
# Take note, any images with the "iso" format is essentially made to be
# deployed somewhere (e.g., desktop, homelab server, VPS).

[tokyo]
systems = [
  "x86_64-linux"
]
format = "iso"

[bootstrap]
systems = [
  "x86_64-linux",
]
format = "install-iso"
nixpkgs-channel = "nixos-unstable-small"
