#! /bin/sh

# - Kill Programs if already running

killall sxhkd;
killall dunst; 
killall thunar; 

#killall emacs;

# - Configuration

setxkbmap br &
xrandr --output HDMI-1 --brightness 1 &

# - Start Programs

sxhkd -c $HOME/.config/bspwm/conf/sxhkdrc & # Keyboard Shortcuts
dunst & # Notifcations
$HOME/.config/polybar/launch.sh & #Bar
imwheel &


# - Start daemons

thunar --daemon &
lxqt-policykit-agent &

#emacs --daemon &

# - Appearence
xsetroot -cursor_name left_ptr &


