# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "sd_mod"
        "usbhid"
      ];
    };
    kernelModules = ["kvm-intel"];
    kernelParams = [
      "quiet"
    ];
  };

  services.undervolt = {
    enable = true;
    coreOffset = -90;
    gpuOffset = -30;
  };

  services.auto-cpufreq.enable = true;

  powerManagement = {
    enable = true;
    # cpufreq = {
    #   min = 400000;
    #   max = 3100000;
    # };
  };

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
