#! /bin/sh

sh $HOME/.config/bspwm/init/start-apps &

#repeat rate
xset r rate 300 50


# - variables
alias bc='bspc config'
alias br='bspc rule'

bspc monitor HDMI1 -d 1 2 3 4 5 6
bspc monitor HDMI1 -d 1 2 3 4 5 6

#Others
bc border_width 2
bc window_gap 10 

bc split_ratio 0.52
bc borderless_monocle true
bc gapless_monocle false

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#8da3b9'


bspc config focus_follows_pointer false

#rules
#br -a Zathura state=tiled
#bspc rule -a Emacs state=tiled

bspc config automatic_scheme spiral
bspc config initial_polarity first_child
br -a Firefox desktop=^2

#fix netbeans not loading problem
wmname compiz & 

