# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot = {
    initrd = {
      postDeviceCommands = lib.mkAfter ''
          zfs rollback -r zroot/root@blank
          zfs rollback -r zroot/home@blank
       '';
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "sd_mod"
        "usbhid"
      ];
    };
    kernelModules = [ "kvm-intel" ];
    kernelParams = [
      "quiet"
    ];
  };

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
