format = """
[  $username$hostname ]\
(bold bg:black fg:white)\
[]\
(bold bg:purple fg:black)\
[\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
]\
(bold bg:purple fg:black)\
[]\
(bold bg:none fg:purple) \
$nix_shell\
$memory_usage\
$env_var\
[バカ](bold bg:none fg:white)\
$directory\
$status\
$character  \
"""

[fill]
symbol = " "

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold bg:black fg:white"
style_root = "bold bg:black fg:white"

[hostname]
ssh_only = true
style = "bg:black fg:white"
format = "[@$hostname]($style)"

[git_branch]
symbol = " "
format = " on [$symbol$branch]($style) "
style = "bold bg:purple fg:black"

[git_commit]
style = "bold bg:purple fg:black"

[git_state]
style = "bold bg:purple fg:black"

[git_status]
style = "bold bg:purple fg:black"

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "./"
style = "bold bg:none fg:yellow"

[status]
disabled = false
symbol = '✗'

[line_break]
disabled = true

[character]
error_symbol = "[](bold red)"
success_symbol = "[](bold white)"
