token_nix: ENC[AES256_GCM,data:zNzZXRIx64tOA2+EI6/sI3wMg4v59e7ziv5nJwOZw9ZP3Qu4HrUIPk7LrwSz45+Egm4VmJTjf+wbveF+H4fk3QuQdv6Nn8QuJr/qOCqxhDCqv5UDUU3eoMu2obV5,iv:n1N6rddcxOmdMjOY1lK4fzZCCmG3Yazyao7wPfnjrYI=,tag:wnIm7OjLkfNcD1ShbMCxbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vqkhlwzs9hhsnl2yms37p4fctpvaznta5sk7kshxvmj0u9u5c3jqvk4nh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINXNNSHR5dUZ6MFZRZEt6
            eEI0dlU4MXcyNXRBK3huVWRkUmFRSXIyKzA4CklaUzI5cUdjdS9sem9vUUkrcWRn
            OTVUZnh6aVpZNEQ4dkhPOTloSmhnT1kKLS0tIEUzNS9kcnZpaUpDZVp6V1k5ellp
            dGJ1YUttbkhTajBWOGF3T3pOd1BId2MKlsBz77/+rHx4FSSiP2At0k4BeJt/Alne
            fG+pFh+C8Mb4xJlj+KBip0Pw5j5T8i2dJKc7aJNyC0NSDiz2It0fyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-12T05:06:14Z"
    mac: ENC[AES256_GCM,data:X8q6Ro/mxT4lNSA6BC/gNGgJwtKseI29rE1hASIq/9ksEyakS0Mtqgv3W3Kb3V2HNBrmDZkzri89G7Pi2qrDU10TJDoqvCSSaZ7KZUJ+t+YP3lqGF3HQScIxRO720URYrhYEWs+5mjI3jW5Lsi2m4qvzRCkxdgChsZs6cxP9SM4=,iv:V4m+ggw3Om47qN044/aR3JEPZOz5oMDaxmXtHkljCNk=,tag:E4sAjF8Tw+UfXObh4mRFuQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
