name: "Cache outputs"
on:
  push:
    branches:
      - main
      - staging
jobs:
  build-custom-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: DeterminateSystems/nix-installer-action@v10
        with:
          extra-conf: |
            keep-going = true
      - name: Build custom packages
        run: nix build -f ./pkgs --impure
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
