name: "build"
on:
  push:
    branches:
      - main
      - staging
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@75ffa7fc743135e1db864b699d78402ccc8ed988
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - uses: DeterminateSystems/flake-checker-action@v7
      - name: cache
        uses: cachix/cachix-action@v14
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: yggdrasil
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: build
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
        run: |
          nix build --accept-flake-config --file ./pkgs --impure
  iso:
    permissions:
      contents: write
      actions: read
    strategy:
      matrix:
        arch:
          - "x86_64-linux"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@75ffa7fc743135e1db864b699d78402ccc8ed988
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - uses: DeterminateSystems/flake-checker-action@v7
      - name: bootstrap
        env:
          NIXPKGS_ALLOW_BROKEN: "1"
          NIXPKGS_ALLOW_UNFREE: "1"
        run: |
          nix build --accept-flake-config .#images.${{ matrix.arch }}.bootstrap-install-iso --impure --out-link iso-result
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest --cleanup-tag --yes || true
          gh release create latest --prerelease --generate-notes iso-result/iso/*.iso
