name: "Cache outputs"
on:
  push:
    branches:
      - main
      - staging
jobs:
  build-custom-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - uses: DeterminateSystems/nix-installer-action@v10
        with:
          extra-conf: |
            keep-going = true
      - name: Prepare push to binary cache
        uses: cachix/cachix-action@v14
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: diegofarias
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build custom packages
        run: nix build -f ./pkgs --impure
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
