name: "check"
on:
  - pull_request
  - push
jobs:
  outputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@75ffa7fc743135e1db864b699d78402ccc8ed988
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - uses: DeterminateSystems/flake-checker-action@v7
      - name: outputs
        run: |
          nix flake check --impure  --keep-going --accept-flake-config
        env:
          NIXPKGS_ALLOW_BROKEN: "1"
          NIXPKGS_ALLOW_UNFREE: "1"
          NIXPKGS_ALLOW_INSECURE: "1"
          NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: "1"
