name: "check"
on:
  pull_request:
  push:
    branches:
      - main
      - staging
jobs:
  outputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - name: lockfile
        uses: DeterminateSystems/flake-checker-action@v5
      - name: outputs
        run: |
          nix flake check --impure --accept-flake-config --keep-going
        env:
          NIXPKGS_ALLOW_BROKEN: "1"
          NIXPKGS_ALLOW_UNFREE: "1"
          NIXPKGS_ALLOW_INSECURE: "1"
          NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: "1"
