name: "checks"
on:
  pull_request:
  push:
    branches:
      - master
      - develop
  schedule:
    - cron: '5 10 * * 4' # At 10:05 on Thursday.
jobs:
  check-outputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v5
      - name: Check flake lockfile
        uses: DeterminateSystems/flake-checker-action@v5
      - name: Check flake outputs
        run: |
          nix flake check --impure --no-build --accept-flake-config
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
