name: "format"
on: push
jobs:
  code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@75ffa7fc743135e1db864b699d78402ccc8ed988
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - uses: DeterminateSystems/flake-checker-action@v7
      - name: format
        run: |
          nix fmt --accept-flake-config
      - name: commit-changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "actions: format" || echo "no changes to commit"
      - name: push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH=${{ github.ref }}
          git push origin "${BRANCH#refs/heads/}"
