name: "packages"
on:
  push:
    branches:
      - master
      - develop
jobs:
  build-custom-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: DeterminateSystems/nix-installer-action@v5
        with:
          extra-conf: |
            keep-going = true
      - name: packages
        run: nix build -f ./pkgs --impure
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
