# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" "nvme" ];
    initrd.kernelModules = [ "dm-snapshot" ];
    kernelModules = [ "kvm-intel" "wl" ];
    extraModulePackages = [ ];

    # Refuse ICMP echo requests on my desktop/laptop; nobody has any business
    # pinging them, unlike my servers.
    kernel.sysctl."net.ipv4.icmp_echo_ignore_broadcasts" = 1;
  };
  fileSystems = {

    "/" =
      {
        device = "/dev/disk/by-label/nixos-root";
        fsType = "ext4";
      };

    "/home" =
      {
        device = "/dev/disk/by-label/nixos-home";
        fsType = "ext4";
      };

    "/boot" =
      {
        device = "/dev/disk/by-label/nixos-boot";
        fsType = "vfat";
      };
  };
  swapDevices =
    [{ device = "/dev/disk/by-label/nixos-swap"; }];


  networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault " x86_64-linux ";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

